### ISSUE TITLE
Create folders recursively for custom output{Dir|File}

### ISSUE THREAD

**Issue by seanzx85** [karma-runner/karma-junit-reporter#48]
If i have the output file defined it caused ENOENT errors because it can't create the folder for the file name.

In this case I have the following:
```
        junitReporter: {
            outputDir: 'test/client/results/junit',
            outputFile: 'test-results.xml',
            suite: ''
        },
```

I receive the following error
```
21 07 2015 10:33:44.303:WARN [reporter.junit]: Cannot write JUnit xml
	ENOENT, open '/Users/XXXX/Code/XXX/XXX/test/client/results/junit/PhantomJS_1.9.8_(Mac_OS_X_0.0.0)/test-results.xml'
```

If I make the folder to match the name above, it works.  However, these change quite regularly, so this should be handled by the reporter.  I think it just needs to make the directory first before attempting file creation.

**Comment by killercentury** [comment]
Found the same issue

**Comment by kether667** [comment]
+1 
same here

**Comment by Dignifiedquire** [comment]
@kether667 can you confirm that #49 fixes the issue?

**Comment by kether667** [comment]
just tested, i confirm that #49 fixes #48

**Comment by Dignifiedquire** [comment]
Should be fixed in `0.3.3`

**Comment by merlosy** [comment]
Hi all,

It seems I still have the issue:
```
PhantomJS 1.9.8 (Linux 0.0.0): Executed 21 of 23 (skipped 2) SUCCESS (0.047 secs / 0.099 secs)
[33m25 08 2015 11:33:46.243:WARN [reporter.junit]: [39mCannot write JUnit xml
	ENOENT, open '/test/results/PhantomJS_1.9.8_(Linux_0.0.0)/test-results-jenkins.xml'
```
I'm using:
- node v0.12.7
- grunt-cli v0.1.13
- grunt v0.4.5
- bower v1.4.1
- karma-junit-reporter v0.3.3

Regarding my karma definition:
```
junitReporter: {
      outputDir: '/test/results/',
      outputFile: 'test-results-jenkins.xml'
},
```

I'm trying to build it with Jenkins.

Any ideas?

**Comment by watchwithmike** [comment]
Similar to @merlosy I'm still seeing this problem in 0.3.6

```
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 250 of 250 SUCCESS (7.251 secs / 0.693 secs)
30 09 2015 21:01:52.134:WARN [reporter.junit]: Cannot write JUnit xml
	ENOENT, open '/Users/mike/git/project-name/build/test/PhantomJS_1.9.8_(Mac_OS_X_0.0.0)/test-results.xml'
```

When I role back to 0.2.2 and just use the `outputFile` parameter I get the expected results.

**Comment by adriaanthomas** [comment]
The `NOENT` error looks like #67. The problem is that the browser-specific directory was not created.

**Comment by watchwithmike** [comment]
@adriaanthomas Thank you, I agree that looks like the same problem. I'll await the next release.

**Comment by Dignifiedquire** [comment]
Release was cut this morning
