### ISSUE TITLE
Cannot read property '33038646' of null - karma-junit-reporter/index.js:93:22

### ISSUE THREAD

**Issue by osherx** [karma-runner/karma-junit-reporter#61]
reproduced here
https://github.com/el-net/bs_karma_eval

when run locally as:

```
karma start karma/lc.js
```

reproduction is inconsistent :-( 

full error:

```

Missing error handler on `socket`.
TypeError: Cannot read property '30193015' of null
    at specSuccess.specSkipped.specFailure (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma-junit-reporter/index.js:93:22)
    at onSpecComplete (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/lib/reporters/base.js:78:12)
    at null.<anonymous> (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/lib/events.js:13:22)
    at emit (events.js:129:20)
    at onResult (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/lib/browser.js:216:13)
    at Socket.<anonymous> (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/lib/events.js:13:22)
    at Socket.emit (events.js:129:20)
    at Socket.onevent (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:107:17)
    at Socket.onPacket (/Users/osher/ws/POC/bs_karma_eval/node_modules/karma/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at WebSocket.emit (events.js:129:20)

```

**Comment by osherx** [comment]
hmm. I noted that in some browsers, each time karma launches the browser - a new tab is added to the browser, so I end up running the test on the browser X times - and that could be the source of a race-condition:

It could be that one tab reported results and the test is closed, and then another tab opened to the karma server ends test and tries to report results.

I can propose two alternatives:
1 - hook on registering browsers, as opposed to hook on launched browsers.
Karma will accept any browser tab that opens onto it...
2 - if ending the test `null`s the `suites` object - then it could not be accessed naively in the named line.
 perhaps closing the test and `null`ing it should implement wiser checks.

**Comment by TheSavior** [comment]
This is flaking on us as well. We get a different number of course.

**Comment by TomaszScisloGS** [comment]
Can you elaborate on the solutions that you proposed?

With the newest version 0.3.8 I get the following error:

    var suite = suites[browser.id]
                      ^
TypeError: Cannot read property '72831859' of null
  at [object Object].onBrowserComplete (h:\Projects\WDP\src\web\node_modules\karma-junit-reporter\index.js:102:23)
  at [object Object].<anonymous> (h:\Projects\WDP\src\web\node_modules\karma\lib\events.js:13:22)
  at [object Object].emit (events.js:117:20)
  at [object Object]._onTimeout (h:\Projects\WDP\src\web\node_modules\karma\lib\browser.js:50:15)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by StanleyGoldman** [comment]
I was getting this error regularly in a file watcher scenario. It would work the first time but fail often on subsequent runs. So I did some simple debugging and I found there are three functions at play. onRunStart, onBrowserStart, onRunComplete; they are intended to execute in that order.

I found this error occurs when onRunComplete executes before onBrowserStart.
As soon as I took restartOnFileChange out of my config file. I stopped getting the error.

**Comment by StanleyGoldman** [comment]
Related: https://github.com/karma-runner/karma-junit-reporter/issues/20

**Comment by TomaszScisloGS** [comment]
@StanleyGoldman 
I already have this in my karma-junit-reporter code: https://github.com/robrich/karma-junit-reporter/commit/836f89f04fc95f48278ac1780239127b0dfa81d7 but this hasn't solved my problem.

Can you elaborate on restartOnFileChange flag I cannot find it in karma-junit-reporte plugin doc. Do you have it in karma.config?

Thanks!

**Comment by StanleyGoldman** [comment]
It's a karma setting that I put in my karma.conf.
Taking it out seemed to abate the issue.

**Comment by TomaszScisloGS** [comment]
Thanks @StanleyGoldman 
I don't have this option enabled and I still get this error from time to time

**Comment by pfrandsen** [comment]
I get this error too at random times on our Jenkins server

**Comment by mathiasmoeller** [comment]
+1

**Comment by ianwremmel** [comment]
Is https://github.com/karma-runner/karma-junit-reporter/issues/38 also related?

**Comment by johnament** [comment]
This is flaking for us as well.

**Comment by dcbrwn** [comment]
Encountered this issue after this update:
"karma-phantomjs-launcher": "^0.2.1" ->  "karma-phantomjs-launcher": "^1.0.0"
"phantomjs": "^1.9.18"	 -> "phantomjs-prebuilt": "^2.1.7"

karma-junit version not changed and is 3.8.0

Bug reproduced on both linux (arch, ubuntu 14.04) and windows (10) with different bersions of node (4.2, 4.3) and npm (2.x, 3.x).

All tests are correct and karma works correctly without junit.

```
SUMMARY:
✔ 147 tests completed
[23:04:20] Finished 'test-single' after 8.9 s
07 04 2016 23:04:29.413:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
/home/doc/lab/test/Source/Web/node_modules/karma-junit-reporter/index.js:102
    var suite = suites[browser.id]
                      ^

TypeError: Cannot read property '30530595' of null
    at onBrowserComplete (/home/doc/lab/test/Source/Web/node_modules/karma-junit-reporter/index.js:102:23)
    at null.<anonymous> (/home/doc/lab/test/Source/Web/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:95:20)
    at emit (events.js:182:7)
    at null._onTimeout (/home/doc/lab/test/Source/Web/node_modules/karma/lib/browser.js:50:15)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by Caradonna9** [comment]
I fixed the `Disconnected (1 times), because no message in 10000 ms.` problem by increasing the `browserNoActivityTimeout` setting in karma.config. The default value is 10000 but I found my browser (PhantomJS) was consistently closing due to the `TypeError: Cannot read property '30530595' of null ` before the tests finished running. Increasing to 30000 solved the issue for me.

**Comment by shoesel** [comment]
I already reported it on the karma-runner-project, but maybe that was wrong: [github-karma](https://github.com/karma-runner/karma/issues/1751)
Seems the error only occurs with the karma-junit-reporter:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 3281 of 3302 (skipped 21) SUCCESS (25.1 secs / 23.617 secs)
Missing error handler on 'socket'.
TypeError: Cannot read property '93062136' of null
  at onBrowserComplete (/PATH-TO/node_modules/karma-junit-reporter/index.js:120:23)
  at .<anonymous> (/PATH-TO/node_modules/karma/lib/events.js:13:22)
  at emitTwo (events.js:111:20)
  at emit (events.js:191:7)
  at onComplete (/PATH-TO/node_modules/karma/lib/browser.js:143:13)
  at Socket.<anonymous> (/PATH-TO/node_modules/karma/lib/events.js:13:22)
  at emitTwo (events.js:111:20)
  at Socket.emit (events.js:191:7)
  at Socket.onevent (/PATH-TO/node_modules/socket.io/lib/socket.js:335:8)
  at Socket.onpacket (/PATH-TO/node_modules/socket.io/lib/socket.js:295:12)
  at Client.ondecoded (/PATH-TO/node_modules/socket.io/lib/client.js:193:14)
  at Decoder.Emitter.emit (/PATH-TO/node_modules/component-emitter/index.js:134:20)
  at Decoder.add (/PATH-TO/node_modules/socket.io-parser/index.js:247:12)
  at Client.ondata (/PATH-TO/node_modules/socket.io/lib/client.js:175:18)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Socket.onPacket (/PATH-TO/node_modules/engine.io/lib/socket.js:101:14)
  at emitOne (events.js:96:13)
  at WebSocket.emit (events.js:188:7)
  at WebSocket.Transport.onPacket (/PATH-TO/node_modules/engine.io/lib/transport.js:104:8)
  at WebSocket.Transport.onData (/PATH-TO/node_modules/engine.io/lib/transport.js:115:8)
  at WebSocket.onData (/PATH-TO/node_modules/engine.io/lib/transports/websocket.js:76:30)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/PATH-TO/node_modules/ws/lib/WebSocket.js:816:10)
  at /PATH-TO/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/PATH-TO/node_modules/ws/lib/Receiver.js:364:5)
  at /PATH-TO/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/PATH-TO/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/PATH-TO/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/PATH-TO/node_modules/ws/lib/Receiver.js:451:33)
  at Receiver.add (/PATH-TO/node_modules/ws/lib/Receiver.js:95:24)
  at Socket.realHandler (/PATH-TO/node_modules/ws/lib/WebSocket.js:800:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:172:18)
  at Socket.Readable.push (_stream_readable.js:130:10)
  at TCP.onread (net.js:542:20)

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Disconnectedundefined
```

**Comment by WuDo** [comment]
+1

**Comment by stramel** [comment]
https://github.com/karma-runner/karma/issues/1292

**Comment by hypery2k** [comment]
seems  to be related to usage of the karma-jasmine-html-reporter. If i exclude this reporter in karma everything is working

**Comment by TheSavior** [comment]
Mm. I've gotten this and never used the jasmine reporter.

**Comment by ianwremmel** [comment]
Same here. i use the mocha reporter, the junit reporter, and sometimes the coverage reporter.

**Comment by ibbatta** [comment]
+1 Here

I use karma 1.3.0 and karma-junit-reporter 1.1.0

**Comment by mlc-mlapis** [comment]
The same for me with "karma-htmlfile-reporter".

I use "karma" 1.3.0 and "karma-htmlfile-reporter" 0.3.4 and "phantomjs" 2.1.7.

**Comment by randakar** [comment]
+1

This one is pretty annoying. We also use karma-junit-reporter and karma-jasmine, but no jasmine reporter.
Increasing that timeout appears to do nothing for us either.

**Comment by randakar** [comment]
Alright. A little poking around in index.js seems to confirm that this bug lives in the karma-junit-reporter.
Adding the following snippet in various places that the suites object is accessed *seems* to help.

if( suites == null )
	suites = Object.create(null)

Basically initializing that thing if events fire in a different order.

**Comment by theBull** [comment]
Any chance we can get a PR for this?

**Comment by thatmarvin** [comment]
I can reproduce this consistently as described in https://github.com/karma-runner/karma-junit-reporter/issues/99#issuecomment-263997704. Fix #110 is already merged into master, see if that works for you?

**Comment by randakar** [comment]
I have that fix (https://github.com/karma-runner/karma-junit-reporter/pull/110). It doesn't help, unfortunately. Not sure why though. 
I will have to look into it monday when I get back to work ;)

**Comment by robinj** [comment]
@randakar did you check out the code from master, rather than doing an npm install as the code with the fix hasn't been released yet. I will also look into it on Monday as it seems to be blocking all of our mac users from running their unit tests. 

Not sure if this helps anything, but we have about 100 devs on Windows 7 and eight Redhat CI boxes and none of them seem to have been affected by the latest occurrence of this bug.

**Comment by randakar** [comment]
Yes. I checked out master when I built that patch and tested it. I will need to do some vesting to verify various potential solutions though. I wonder what is happening exactly and why.

**Comment by randakar** [comment]
.. testing. Silly autocorrect.

**Comment by randakar** [comment]
Alright. Quick testing seems to indicate that the commit in master actually changes the behaviour in question.
So my quick-and-dirty patch isn't necessary to fix this.

Nonetheless, I'm still getting the error listed above, so I would not be surprised if something else breaks now due to things running concurrently.

Also, I will send a new PR to implement robinj's suggestion to initialize suites earlier. It doesn't hurt, the whole way it's initialized now is slower and doing it early makes it pretty much immune to races.

**Comment by wesleycho** [comment]
@dignifiedquire I think this can be closed out now given the latest 1.2.0 release

**Comment by wesleycho** [comment]
This should be fixed, going to close this - comment here if it appears again with 1.2.0+ and we can reinvestigate.

**Comment by nemoDreamer** [comment]
I'm still getting this error for `onBrowserComplete` firing after `onRunComplete`. It only happens when I also add the "coverage" reporter/plugin, possibly because some lag is getting exacerbated by the extra overhead?

**Comment by randakar** [comment]
As I've mentioned before: *lots* of modules have this problem. "var suites" got copied all over the place. I bet the coverage reporter has it's own incarnation of it.
